package com.forsuin.betterbuilding;

import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.StairsBlock;
import net.minecraft.client.particle.Particle;
import net.minecraft.particle.ParticleEffect;
import net.minecraft.particle.ParticleTypes;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;


public class BetterBuildingBlocks {
    public static Block DIRT_STAIRS;
    public static Block BEDROCK_STAIRS;
    public static Block GLOWSTONE_STAIRS;
    public static Block STONE_STAIRS;
    public static Block GRANITE_STAIRS;
    public static Block POLISHED_GRANITE_STAIRS;
    public static Block DIORITE_STAIRS;
    public static Block POLISHED_DIORITE_STAIRS;
    public static Block ANDESITE_STAIRS;
    public static Block POLISHED_ANDESITE_STAIRS;
    public static Block GRASS_BLOCK_STAIRS;
    public static Block COARSE_DIRT_STAIRS;
    public static Block PODZOL_STAIRS;
    public static Block SAND_STAIRS;
    public static Block RED_SAND_STAIRS;
    public static Block GRAVEL_STAIRS;
    public static Block GLASS_STAIRS;
    public static Block LAPIS_BLOCK_STAIRS;
    public static Block SANDSTONE_STAIRS;
    public static Block CHISELED_SANDSTONE_STAIRS;
    public static Block CUT_SANDSTONE_STAIRS;
    public static Block WHITE_WOOL_STAIRS;
    public static Block ORANGE_WOOL_STAIRS;
    public static Block MAGENTA_WOOL_STAIRS;
    public static Block LIGHT_BLUE_WOOL_STAIRS;
    public static Block YELLOW_WOOL_STAIRS;
    public static Block LIME_WOOL_STAIRS;
    public static Block PINK_WOOL_STAIRS;
    public static Block GRAY_WOOL_STAIRS;
    public static Block LIGHT_GRAY_WOOL_STAIRS;
    public static Block CYAN_WOOL_STAIRS;
    public static Block PURPLE_WOOL_STAIRS;
    public static Block BLUE_WOOL_STAIRS;
    public static Block BROWN_WOOL_STAIRS;
    public static Block GREEN_WOOL_STAIRS;
    public static Block RED_WOOL_STAIRS;
    public static Block BLACK_WOOL_STAIRS;
    public static Block GOLD_BLOCK_STAIRS;
    public static Block IRON_BLOCK_STAIRS;
    public static Block BRICKS_STAIRS;
    public static Block OBSIDIAN_STAIRS;
    public static Block DIAMOND_BLOCK_STAIRS;
    public static Block ICE_STAIRS;
    public static Block SNOW_BLOCK_STAIRS;
    public static Block CLAY_STAIRS;
    public static Block NETHERRACK_STAIRS;
    public static Block WHITE_STAINED_GLASS_STAIRS;
    public static Block ORANGE_STAINED_GLASS_STAIRS;
    public static Block MAGENTA_STAINED_GLASS_STAIRS;
    public static Block LIGHT_BLUE_STAINED_GLASS_STAIRS;
    public static Block YELLOW_STAINED_GLASS_STAIRS;
    public static Block LIME_STAINED_GLASS_STAIRS;
    public static Block PINK_STAINED_GLASS_STAIRS;
    public static Block GRAY_STAINED_GLASS_STAIRS;
    public static Block LIGHT_GRAY_STAINED_GLASS_STAIRS;
    public static Block CYAN_STAINED_GLASS_STAIRS;
    public static Block PURPLE_STAINED_GLASS_STAIRS;
    public static Block BLUE_STAINED_GLASS_STAIRS;
    public static Block BROWN_STAINED_GLASS_STAIRS;
    public static Block GREEN_STAINED_GLASS_STAIRS;
    public static Block RED_STAINED_GLASS_STAIRS;
    public static Block BLACK_STAINED_GLASS_STAIRS;
    public static Block EMERALD_BLOCK_STAIRS;
    public static Block REDSTONE_BLOCK_STAIRS;
    public static Block WHITE_TERRACOTTA_STAIRS;
    public static Block ORANGE_TERRACOTTA_STAIRS;
    public static Block MAGENTA_TERRACOTTA_STAIRS;
    public static Block LIGHT_BLUE_TERRACOTTA_STAIRS;
    public static Block YELLOW_TERRACOTTA_STAIRS;
    public static Block LIME_TERRACOTTA_STAIRS;
    public static Block PINK_TERRACOTTA_STAIRS;
    public static Block GRAY_TERRACOTTA_STAIRS;
    public static Block LIGHT_GRAY_TERRACOTTA_STAIRS;
    public static Block CYAN_TERRACOTTA_STAIRS;
    public static Block PURPLE_TERRACOTTA_STAIRS;
    public static Block BLUE_TERRACOTTA_STAIRS;
    public static Block BROWN_TERRACOTTA_STAIRS;
    public static Block GREEN_TERRACOTTA_STAIRS;
    public static Block RED_TERRACOTTA_STAIRS;
    public static Block BLACK_TERRACOTTA_STAIRS;
    public static Block SLIME_BLOCK_STAIRS;
    public static Block SEA_LANTERN_STAIRS;
    public static Block TERRACOTTA_STAIRS;
    public static Block COAL_BLOCK_STAIRS;
    public static Block PACKED_ICE_STAIRS;
    public static Block SMOOTH_STONE_STAIRS;
    public static Block FROSTED_ICE_STAIRS;
    public static Block MAGMA_BLOCK_STAIRS;
    public static Block NETHER_WART_BLOCK_STAIRS;
    public static Block BONE_BLOCK_STAIRS;
    public static Block WHITE_GLAZED_TERRACOTTA_STAIRS;
    public static Block ORANGE_GLAZED_TERRACOTTA_STAIRS;
    public static Block MAGENTA_GLAZED_TERRACOTTA_STAIRS;
    public static Block LIGHT_BLUE_GLAZED_TERRACOTTA_STAIRS;
    public static Block YELLOW_GLAZED_TERRACOTTA_STAIRS;
    public static Block LIME_GLAZED_TERRACOTTA_STAIRS;
    public static Block PINK_GLAZED_TERRACOTTA_STAIRS;
    public static Block GRAY_GLAZED_TERRACOTTA_STAIRS;
    public static Block LIGHT_GRAY_GLAZED_TERRACOTTA_STAIRS;
    public static Block CYAN_GLAZED_TERRACOTTA_STAIRS;
    public static Block PURPLE_GLAZED_TERRACOTTA_STAIRS;
    public static Block BLUE_GLAZED_TERRACOTTA_STAIRS;
    public static Block BROWN_GLAZED_TERRACOTTA_STAIRS;
    public static Block GREEN_GLAZED_TERRACOTTA_STAIRS;
    public static Block RED_GLAZED_TERRACOTTA_STAIRS;
    public static Block BLACK_GLAZED_TERRACOTTA_STAIRS;
    public static Block WHITE_CONCRETE_STAIRS;
    public static Block ORANGE_CONCRETE_STAIRS;
    public static Block MAGENTA_CONCRETE_STAIRS;
    public static Block LIGHT_BLUE_CONCRETE_STAIRS;
    public static Block YELLOW_CONCRETE_STAIRS;
    public static Block LIME_CONCRETE_STAIRS;
    public static Block PINK_CONCRETE_STAIRS;
    public static Block GRAY_CONCRETE_STAIRS;
    public static Block LIGHT_GRAY_CONCRETE_STAIRS;
    public static Block CYAN_CONCRETE_STAIRS;
    public static Block PURPLE_CONCRETE_STAIRS;
    public static Block BLUE_CONCRETE_STAIRS;
    public static Block BROWN_CONCRETE_STAIRS;
    public static Block GREEN_CONCRETE_STAIRS;
    public static Block RED_CONCRETE_STAIRS;
    public static Block BLACK_CONCRETE_STAIRS;
    public static Block WHITE_CONCRETE_POWDER_STAIRS;
    public static Block ORANGE_CONCRETE_POWDER_STAIRS;
    public static Block MAGENTA_CONCRETE_POWDER_STAIRS;
    public static Block LIGHT_BLUE_CONCRETE_POWDER_STAIRS;
    public static Block YELLOW_CONCRETE_POWDER_STAIRS;
    public static Block LIME_CONCRETE_POWDER_STAIRS;
    public static Block PINK_CONCRETE_POWDER_STAIRS;
    public static Block GRAY_CONCRETE_POWDER_STAIRS;
    public static Block LIGHT_GRAY_CONCRETE_POWDER_STAIRS;
    public static Block CYAN_CONCRETE_POWDER_STAIRS;
    public static Block PURPLE_CONCRETE_POWDER_STAIRS;
    public static Block BLUE_CONCRETE_POWDER_STAIRS;
    public static Block BROWN_CONCRETE_POWDER_STAIRS;
    public static Block GREEN_CONCRETE_POWDER_STAIRS;
    public static Block RED_CONCRETE_POWDER_STAIRS;
    public static Block BLACK_CONCRETE_POWDER_STAIRS;
    public static Block BLUE_ICE_STAIRS;
    public static Block BAMBOO_STAIRS;
    public static Block HONEY_BLOCK_STAIRS;
    public static Block HONEYCOMB_BLOCK_STAIRS;
    public static Block NETHERITE_BLOCK_STAIRS;
    public static Block ANCIENT_DEBRIS_STAIRS;
    public static Block CRYING_OBSIDIAN_STAIRS;
    public static Block GILDED_BLACKSTONE_STAIRS;
    public static Block CHISELED_NETHER_BRICKS_STAIRS;
    public static Block CRACKED_NETHER_BRICKS_STAIRS;
    public static Block QUARTZ_BRICKS_STAIRS;

    public static Block CANDELABRUM;

    public static void initBlocks() {
        DIRT_STAIRS = registerStairsBlocks("dirt_stairs", Blocks.DIRT);
        BEDROCK_STAIRS = registerStairsBlocks("bedrock_stairs", Blocks.BEDROCK);
        GLOWSTONE_STAIRS = registerStairsBlocks("glowstone_stairs", Blocks.GLOWSTONE);
        STONE_STAIRS = registerStairsBlocks("stone_stairs", Blocks.STONE);
        GRANITE_STAIRS = registerStairsBlocks("granite_stairs", Blocks.GRANITE);
        POLISHED_GRANITE_STAIRS = registerStairsBlocks("polished_granite_stairs", Blocks.POLISHED_GRANITE);
        DIORITE_STAIRS = registerStairsBlocks("diorite_stairs", Blocks.DIORITE);
        POLISHED_DIORITE_STAIRS = registerStairsBlocks("polished_diorite_stairs", Blocks.POLISHED_DIORITE);
        ANDESITE_STAIRS = registerStairsBlocks("andesite_stairs", Blocks.ANDESITE);
        POLISHED_ANDESITE_STAIRS = registerStairsBlocks("polished_andesite_stairs", Blocks.POLISHED_ANDESITE);
        GRASS_BLOCK_STAIRS = registerStairsBlocks("grass_block_stairs", Blocks.GRASS_BLOCK);
        COARSE_DIRT_STAIRS = registerStairsBlocks("coarse_dirt_stairs", Blocks.COARSE_DIRT);
        PODZOL_STAIRS = registerStairsBlocks("podzol_stairs", Blocks.PODZOL);
        SAND_STAIRS = registerStairsBlocks("sand_stairs", Blocks.SAND);
        RED_SAND_STAIRS = registerStairsBlocks("red_sand_stairs", Blocks.RED_SAND);
        GRAVEL_STAIRS = registerStairsBlocks("gravel_stairs", Blocks.GRAVEL);
        GLASS_STAIRS = registerStairsBlocks("glass_stairs", Blocks.GLASS);
        LAPIS_BLOCK_STAIRS = registerStairsBlocks("lapis_block_stairs", Blocks.LAPIS_BLOCK);
        SANDSTONE_STAIRS = registerStairsBlocks("sandstone_stairs", Blocks.SANDSTONE);
        CHISELED_SANDSTONE_STAIRS = registerStairsBlocks("chiseled_sandstone_stairs", Blocks.CHISELED_SANDSTONE);
        CUT_SANDSTONE_STAIRS = registerStairsBlocks("cut_sandstone_stairs", Blocks.CUT_SANDSTONE);
        WHITE_WOOL_STAIRS = registerStairsBlocks("white_wool_stairs", Blocks.WHITE_WOOL);
        ORANGE_WOOL_STAIRS = registerStairsBlocks("orange_wool_stairs", Blocks.ORANGE_WOOL);
        MAGENTA_WOOL_STAIRS = registerStairsBlocks("magenta_wool_stairs", Blocks.MAGENTA_WOOL);
        LIGHT_BLUE_WOOL_STAIRS = registerStairsBlocks("light_blue_wool_stairs", Blocks.LIGHT_BLUE_WOOL);
        YELLOW_WOOL_STAIRS = registerStairsBlocks("yellow_wool_stairs", Blocks.YELLOW_WOOL);
        LIME_WOOL_STAIRS = registerStairsBlocks("lime_wool_stairs", Blocks.LIME_WOOL);
        PINK_WOOL_STAIRS = registerStairsBlocks("pink_wool_stairs", Blocks.PINK_WOOL);
        GRAY_WOOL_STAIRS = registerStairsBlocks("gray_wool_stairs", Blocks.GRAY_WOOL);
        LIGHT_GRAY_WOOL_STAIRS = registerStairsBlocks("light_gray_wool_stairs", Blocks.LIGHT_GRAY_WOOL);
        CYAN_WOOL_STAIRS = registerStairsBlocks("cyan_wool_stairs", Blocks.CYAN_WOOL);
        PURPLE_WOOL_STAIRS = registerStairsBlocks("purple_wool_stairs", Blocks.PURPLE_WOOL);
        BLUE_WOOL_STAIRS = registerStairsBlocks("blue_wool_stairs", Blocks.BLUE_WOOL);
        BROWN_WOOL_STAIRS = registerStairsBlocks("brown_wool_stairs", Blocks.BROWN_WOOL);
        GREEN_WOOL_STAIRS = registerStairsBlocks("green_wool_stairs", Blocks.GREEN_WOOL);
        RED_WOOL_STAIRS = registerStairsBlocks("red_wool_stairs", Blocks.RED_WOOL);
        BLACK_WOOL_STAIRS = registerStairsBlocks("black_wool_stairs", Blocks.BLACK_WOOL);
        GOLD_BLOCK_STAIRS = registerStairsBlocks("gold_block_stairs", Blocks.GOLD_BLOCK);
        IRON_BLOCK_STAIRS = registerStairsBlocks("iron_block_stairs", Blocks.IRON_BLOCK);
        BRICKS_STAIRS = registerStairsBlocks("bricks_stairs", Blocks.BRICKS);
        OBSIDIAN_STAIRS = registerStairsBlocks("obsidian_stairs", Blocks.OBSIDIAN);
        DIAMOND_BLOCK_STAIRS = registerStairsBlocks("diamond_block_stairs", Blocks.DIAMOND_BLOCK);
        ICE_STAIRS = registerStairsBlocks("ice_stairs", Blocks.ICE);
        SNOW_BLOCK_STAIRS = registerStairsBlocks("snow_block_stairs", Blocks.SNOW_BLOCK);
        CLAY_STAIRS = registerStairsBlocks("clay_stairs", Blocks.CLAY);
        NETHERRACK_STAIRS = registerStairsBlocks("netherrack_stairs", Blocks.NETHERRACK);
        WHITE_STAINED_GLASS_STAIRS = registerStairsBlocks("white_stained_glass_stairs", Blocks.WHITE_STAINED_GLASS);
        ORANGE_STAINED_GLASS_STAIRS = registerStairsBlocks("orange_stained_glass_stairs", Blocks.ORANGE_STAINED_GLASS);
        MAGENTA_STAINED_GLASS_STAIRS = registerStairsBlocks("magenta_stained_glass_stairs", Blocks.MAGENTA_STAINED_GLASS);
        LIGHT_BLUE_STAINED_GLASS_STAIRS = registerStairsBlocks("light_blue_stained_glass_stairs", Blocks.LIGHT_BLUE_STAINED_GLASS);
        YELLOW_STAINED_GLASS_STAIRS = registerStairsBlocks("yellow_stained_glass_stairs", Blocks.YELLOW_STAINED_GLASS);
        LIME_STAINED_GLASS_STAIRS = registerStairsBlocks("lime_stained_glass_stairs", Blocks.LIME_STAINED_GLASS);
        PINK_STAINED_GLASS_STAIRS = registerStairsBlocks("pink_stained_glass_stairs", Blocks.PINK_STAINED_GLASS);
        GRAY_STAINED_GLASS_STAIRS = registerStairsBlocks("gray_stained_glass_stairs", Blocks.GRAY_STAINED_GLASS);
        LIGHT_GRAY_STAINED_GLASS_STAIRS = registerStairsBlocks("light_gray_stained_glass_stairs", Blocks.LIGHT_GRAY_STAINED_GLASS);
        CYAN_STAINED_GLASS_STAIRS = registerStairsBlocks("cyan_stained_glass_stairs", Blocks.CYAN_STAINED_GLASS);
        PURPLE_STAINED_GLASS_STAIRS = registerStairsBlocks("purple_stained_glass_stairs", Blocks.PURPLE_STAINED_GLASS);
        BLUE_STAINED_GLASS_STAIRS = registerStairsBlocks("blue_stained_glass_stairs", Blocks.BLUE_STAINED_GLASS);
        BROWN_STAINED_GLASS_STAIRS = registerStairsBlocks("brown_stained_glass_stairs", Blocks.BROWN_STAINED_GLASS);
        GREEN_STAINED_GLASS_STAIRS = registerStairsBlocks("green_stained_glass_stairs", Blocks.GREEN_STAINED_GLASS);
        RED_STAINED_GLASS_STAIRS = registerStairsBlocks("red_stained_glass_stairs", Blocks.RED_STAINED_GLASS);
        BLACK_STAINED_GLASS_STAIRS = registerStairsBlocks("black_stained_glass_stairs", Blocks.BLACK_STAINED_GLASS);
        EMERALD_BLOCK_STAIRS = registerStairsBlocks("emerald_block_stairs", Blocks.EMERALD_BLOCK);
        REDSTONE_BLOCK_STAIRS = registerStairsBlocks("redstone_block_stairs", Blocks.REDSTONE_BLOCK);
        WHITE_TERRACOTTA_STAIRS = registerStairsBlocks("white_terracotta_stairs", Blocks.WHITE_TERRACOTTA);
        ORANGE_TERRACOTTA_STAIRS = registerStairsBlocks("orange_terracotta_stairs", Blocks.ORANGE_TERRACOTTA);
        MAGENTA_TERRACOTTA_STAIRS = registerStairsBlocks("magenta_terracotta_stairs", Blocks.MAGENTA_TERRACOTTA);
        LIGHT_BLUE_TERRACOTTA_STAIRS = registerStairsBlocks("light_blue_terracotta_stairs", Blocks.LIGHT_BLUE_TERRACOTTA);
        YELLOW_TERRACOTTA_STAIRS = registerStairsBlocks("yellow_terracotta_stairs", Blocks.YELLOW_TERRACOTTA);
        LIME_TERRACOTTA_STAIRS = registerStairsBlocks("lime_terracotta_stairs", Blocks.LIME_TERRACOTTA);
        PINK_TERRACOTTA_STAIRS = registerStairsBlocks("pink_terracotta_stairs", Blocks.PINK_TERRACOTTA);
        GRAY_TERRACOTTA_STAIRS = registerStairsBlocks("gray_terracotta_stairs", Blocks.GRAY_TERRACOTTA);
        LIGHT_GRAY_TERRACOTTA_STAIRS = registerStairsBlocks("light_gray_terracotta_stairs", Blocks.LIGHT_GRAY_TERRACOTTA);
        CYAN_TERRACOTTA_STAIRS = registerStairsBlocks("cyan_terracotta_stairs", Blocks.CYAN_TERRACOTTA);
        PURPLE_TERRACOTTA_STAIRS = registerStairsBlocks("purple_terracotta_stairs", Blocks.PURPLE_TERRACOTTA);
        BLUE_TERRACOTTA_STAIRS = registerStairsBlocks("blue_terracotta_stairs", Blocks.BLUE_TERRACOTTA);
        BROWN_TERRACOTTA_STAIRS = registerStairsBlocks("brown_terracotta_stairs", Blocks.BROWN_TERRACOTTA);
        GREEN_TERRACOTTA_STAIRS = registerStairsBlocks("green_terracotta_stairs", Blocks.GREEN_TERRACOTTA);
        RED_TERRACOTTA_STAIRS = registerStairsBlocks("red_terracotta_stairs", Blocks.RED_TERRACOTTA);
        BLACK_TERRACOTTA_STAIRS = registerStairsBlocks("black_terracotta_stairs", Blocks.BLACK_TERRACOTTA);
        SLIME_BLOCK_STAIRS = registerStairsBlocks("slime_block_stairs", Blocks.SLIME_BLOCK);
        SEA_LANTERN_STAIRS = registerStairsBlocks("sea_lantern_stairs", Blocks.SEA_LANTERN);
        TERRACOTTA_STAIRS = registerStairsBlocks("terracotta_stairs", Blocks.TERRACOTTA);
        COAL_BLOCK_STAIRS = registerStairsBlocks("coal_block_stairs", Blocks.COAL_BLOCK);
        PACKED_ICE_STAIRS = registerStairsBlocks("packed_ice_stairs", Blocks.PACKED_ICE);
        SMOOTH_STONE_STAIRS = registerStairsBlocks("smooth_stone_stairs", Blocks.SMOOTH_STONE);
        FROSTED_ICE_STAIRS = registerStairsBlocks("frosted_ice_stairs", Blocks.FROSTED_ICE);
        MAGMA_BLOCK_STAIRS = registerStairsBlocks("magma_block_stairs", Blocks.MAGMA_BLOCK);
        NETHER_WART_BLOCK_STAIRS = registerStairsBlocks("nether_wart_block_stairs", Blocks.NETHER_WART_BLOCK);
        BONE_BLOCK_STAIRS = registerStairsBlocks("bone_block_stairs", Blocks.BONE_BLOCK);
        WHITE_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("white_glazed_terracotta_stairs", Blocks.WHITE_GLAZED_TERRACOTTA);
        ORANGE_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("orange_glazed_terracotta_stairs", Blocks.ORANGE_GLAZED_TERRACOTTA);
        MAGENTA_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("magenta_glazed_terracotta_stairs", Blocks.MAGENTA_GLAZED_TERRACOTTA);
        LIGHT_BLUE_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("light_blue_glazed_terracotta_stairs", Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA);
        YELLOW_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("yellow_glazed_terracotta_stairs", Blocks.YELLOW_GLAZED_TERRACOTTA);
        LIME_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("lime_glazed_terracotta_stairs", Blocks.LIME_GLAZED_TERRACOTTA);
        PINK_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("pink_glazed_terracotta_stairs", Blocks.PINK_GLAZED_TERRACOTTA);
        GRAY_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("gray_glazed_terracotta_stairs", Blocks.GRAY_GLAZED_TERRACOTTA);
        LIGHT_GRAY_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("light_gray_glazed_terracotta_stairs", Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA);
        CYAN_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("cyan_glazed_terracotta_stairs", Blocks.CYAN_GLAZED_TERRACOTTA);
        PURPLE_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("purple_glazed_terracotta_stairs", Blocks.PURPLE_GLAZED_TERRACOTTA);
        BLUE_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("blue_glazed_terracotta_stairs", Blocks.BLUE_GLAZED_TERRACOTTA);
        BROWN_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("brown_glazed_terracotta_stairs", Blocks.BROWN_GLAZED_TERRACOTTA);
        GREEN_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("green_glazed_terracotta_stairs", Blocks.GREEN_GLAZED_TERRACOTTA);
        RED_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("red_glazed_terracotta_stairs", Blocks.RED_GLAZED_TERRACOTTA);
        BLACK_GLAZED_TERRACOTTA_STAIRS = registerStairsBlocks("black_glazed_terracotta_stairs", Blocks.BLUE_GLAZED_TERRACOTTA);
        WHITE_CONCRETE_STAIRS = registerStairsBlocks("white_concrete_stairs", Blocks.WHITE_CONCRETE);
        ORANGE_CONCRETE_STAIRS = registerStairsBlocks("orange_concrete_stairs", Blocks.ORANGE_CONCRETE);
        MAGENTA_CONCRETE_STAIRS = registerStairsBlocks("magenta_concrete_stairs", Blocks.MAGENTA_CONCRETE);
        LIGHT_BLUE_CONCRETE_STAIRS = registerStairsBlocks("light_blue_concrete_stairs", Blocks.LIGHT_BLUE_CONCRETE);
        YELLOW_CONCRETE_STAIRS = registerStairsBlocks("yellow_concrete_stairs", Blocks.YELLOW_CONCRETE);
        LIME_CONCRETE_STAIRS = registerStairsBlocks("lime_concrete_stairs", Blocks.LIME_CONCRETE);
        PINK_CONCRETE_STAIRS = registerStairsBlocks("pink_concrete_stairs", Blocks.PINK_CONCRETE);
        GRAY_CONCRETE_STAIRS = registerStairsBlocks("gray_concrete_stairs", Blocks.GRAY_CONCRETE);
        LIGHT_GRAY_CONCRETE_STAIRS = registerStairsBlocks("light_gray_concrete_stairs", Blocks.LIGHT_GRAY_CONCRETE);
        CYAN_CONCRETE_STAIRS = registerStairsBlocks("cyan_concrete_stairs", Blocks.CYAN_CONCRETE);
        PURPLE_CONCRETE_STAIRS = registerStairsBlocks("purple_concrete_stairs", Blocks.PURPLE_CONCRETE);
        BLUE_CONCRETE_STAIRS = registerStairsBlocks("blue_concrete_stairs", Blocks.BLUE_CONCRETE);
        BROWN_CONCRETE_STAIRS = registerStairsBlocks("brown_concrete_stairs", Blocks.BROWN_CONCRETE);
        GREEN_CONCRETE_STAIRS = registerStairsBlocks("green_concrete_stairs", Blocks.GREEN_CONCRETE);
        RED_CONCRETE_STAIRS = registerStairsBlocks("red_concrete_stairs", Blocks.RED_CONCRETE);
        BLACK_CONCRETE_STAIRS = registerStairsBlocks("black_concrete_stairs", Blocks.BLACK_CONCRETE);
        WHITE_CONCRETE_POWDER_STAIRS = registerStairsBlocks("white_concrete_powder_stairs", Blocks.WHITE_CONCRETE_POWDER);
        ORANGE_CONCRETE_POWDER_STAIRS = registerStairsBlocks("orange_concrete_powder_stairs", Blocks.ORANGE_CONCRETE_POWDER);
        MAGENTA_CONCRETE_POWDER_STAIRS = registerStairsBlocks("magenta_concrete_powder_stairs", Blocks.MAGENTA_CONCRETE_POWDER);
        LIGHT_BLUE_CONCRETE_POWDER_STAIRS = registerStairsBlocks("light_blue_concrete_powder_stairs", Blocks.LIGHT_BLUE_CONCRETE_POWDER);
        YELLOW_CONCRETE_POWDER_STAIRS = registerStairsBlocks("yellow_concrete_powder_stairs", Blocks.YELLOW_CONCRETE_POWDER);
        LIME_CONCRETE_POWDER_STAIRS = registerStairsBlocks("lime_concrete_powder_stairs", Blocks.LIME_CONCRETE_POWDER);
        PINK_CONCRETE_POWDER_STAIRS = registerStairsBlocks("pink_concrete_powder_stairs", Blocks.PINK_CONCRETE_POWDER);
        GRAY_CONCRETE_POWDER_STAIRS = registerStairsBlocks("gray_concrete_powder_stairs", Blocks.GRAY_CONCRETE_POWDER);
        LIGHT_GRAY_CONCRETE_POWDER_STAIRS = registerStairsBlocks("light_gray_concrete_powder_stairs", Blocks.LIGHT_GRAY_CONCRETE_POWDER);
        CYAN_CONCRETE_POWDER_STAIRS = registerStairsBlocks("cyan_concrete_powder_stairs", Blocks.CYAN_CONCRETE_POWDER);
        PURPLE_CONCRETE_POWDER_STAIRS = registerStairsBlocks("purple_concrete_powder_stairs", Blocks.PURPLE_CONCRETE_POWDER);
        BLUE_CONCRETE_POWDER_STAIRS = registerStairsBlocks("blue_concrete_powder_stairs", Blocks.BLUE_CONCRETE_POWDER);
        BROWN_CONCRETE_POWDER_STAIRS = registerStairsBlocks("brown_concrete_powder_stairs", Blocks.BROWN_CONCRETE_POWDER);
        GREEN_CONCRETE_POWDER_STAIRS = registerStairsBlocks("green_concrete_powder_stairs", Blocks.GREEN_CONCRETE_POWDER);
        RED_CONCRETE_POWDER_STAIRS = registerStairsBlocks("red_concrete_powder_stairs", Blocks.RED_CONCRETE_POWDER);
        BLACK_CONCRETE_POWDER_STAIRS = registerStairsBlocks("black_concrete_powder_stairs", Blocks.BLACK_CONCRETE_POWDER);
        BLUE_ICE_STAIRS = registerStairsBlocks("blue_ice_stairs", Blocks.BLUE_ICE);
        BAMBOO_STAIRS = registerStairsBlocks("bamboo_stairs", Blocks.BAMBOO);
        HONEY_BLOCK_STAIRS = registerStairsBlocks("honey_block_stairs", Blocks.HONEY_BLOCK);
        HONEYCOMB_BLOCK_STAIRS = registerStairsBlocks("honeycomb_block_stairs", Blocks.HONEYCOMB_BLOCK);
        NETHERITE_BLOCK_STAIRS = registerStairsBlocks("netherite_block_stairs", Blocks.NETHERITE_BLOCK);
        ANCIENT_DEBRIS_STAIRS = registerStairsBlocks("ancient_debris_stairs", Blocks.ANCIENT_DEBRIS);
        CRYING_OBSIDIAN_STAIRS = registerStairsBlocks("crying_obsidian_stairs", Blocks.CRYING_OBSIDIAN);
        GILDED_BLACKSTONE_STAIRS = registerStairsBlocks("gilded_blackstone_stairs", Blocks.GILDED_BLACKSTONE);
        CHISELED_NETHER_BRICKS_STAIRS = registerStairsBlocks("chiseled_nether_bricks_stairs", Blocks.CHISELED_NETHER_BRICKS);
        CRACKED_NETHER_BRICKS_STAIRS = registerStairsBlocks("cracked_nether_bricks_stairs", Blocks.CRACKED_NETHER_BRICKS);
        QUARTZ_BRICKS_STAIRS = registerStairsBlocks("quartz_bricks_stairs", Blocks.QUARTZ_BRICKS);

        CANDELABRUM = registerLightBlocks("candelabrum", Blocks.TORCH, ParticleTypes.FLAME);
    }

    public static StairsBlock registerStairsBlocks(String name, Block block) {
        Identifier id = new Identifier(BetterBuilding.MOD_ID, name);
        BetterBuildingStairs newBlock;
        if(block == Blocks.GRASS_BLOCK){
            newBlock = new BetterBuildingBlockDirt(block);
        }
        else{
            newBlock = new BetterBuildingStairs(block);
        }

        return Registry.register(Registry.BLOCK, id, newBlock);

    }

    public static BetterBuildingLights registerLightBlocks(String name, Block block, ParticleEffect particle){
        Identifier id = new Identifier(BetterBuilding.MOD_ID, name);

        BetterBuildingLights newBlock = new BetterBuildingLights(FabricBlockSettings.copy(block), particle);

        return  Registry.register(Registry.BLOCK, id, newBlock);
    }

}
